import "server-only";
import { Prisma } from "@prisma/client";
import { getDb } from "@/lib/db";
import { env } from "@/lib/env";
import { redact } from "@/lib/activity/redact";
import { recordActivity } from "@/lib/activity/record";
import { AstonAiUnavailable, groqChat, type GroqDeps } from "../groq";
import { extractJson } from "../site/assemble";
import {
  detailsSchema, detectKind, KIND_LABEL, normalizeSections, SCRIPT_KINDS,
  type ScriptDetails, type ScriptKind, type ScriptSection,
} from "./format";

/**
 * Teleprompter scripts: generated by Groq (server-side only), then edited,
 * saved and reused from the script library. Generation, editing and playback
 * are separate operations — playback never changes the stored script.
 */

type Row = Prisma.AstonScriptGetPayload<object>;

export class ScriptError extends Error {
  constructor(message: string, public status = 400) { super(message); this.name = "ScriptError"; }
}

export interface ScriptDTO {
  id: string; title: string; kind: ScriptKind; kindLabel: string; businessType: string | null;
  details: ScriptDetails; sections: ScriptSection[]; request: string; saved: boolean;
  createdAt: string; updatedAt: string;
}

export function toScriptDTO(r: Row): ScriptDTO {
  const kind = ((SCRIPT_KINDS as readonly string[]).includes(r.kind) ? r.kind : "general") as ScriptKind;
  return {
    id: r.id, title: r.title, kind, kindLabel: KIND_LABEL[kind], businessType: r.businessType,
    details: (r.details as ScriptDetails | null) ?? {}, sections: normalizeSections(r.content), request: r.request, saved: r.saved,
    createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString(),
  };
}

const GUIDE: Record<ScriptKind, string> = {
  cold_call: "A phone cold call to a local business owner. Sections: Opening (permission-based, under 20 seconds), Customer needs (2-3 open questions), Service introduction (tie to what they said), Benefits (2-3, in their terms), Objection handling (the 3 most likely, each as a client line + your reply), Closing and next steps (ask for a demo or a meeting time).",
  instagram_dm: "Instagram direct messages. Sections: First message (short, personal, references their page; no hard sell), If they reply, Follow-up if no reply (after 2-3 days), Booking the demo. Each 'you' line is one message, 1-3 short sentences, friendly.",
  whatsapp: "WhatsApp pitch messages. Sections: Opening message, Short value message, If they ask the price, Follow-up if no reply, Booking the demo. Each 'you' line is one message; warm, respectful, no spam tone.",
  zoom_demo: "A live Zoom/video website demo. Sections: Welcome & agenda, Understanding their needs, Walking through the demo (what to show and say at each step, with [Share screen]-style directions), Pricing & what's included, Handling objections, Next step.",
  follow_up: "A follow-up conversation after an earlier pitch or demo. Sections: Re-opening (reference the last conversation), Checking where they are, Answering open questions, Handling objections, Next step.",
  objections: "Objection handling. Sections, one per objection: e.g. \"It's too expensive\", \"I already have Instagram\", \"I don't have time\", \"I'll think about it\", \"I had a bad experience before\". In each: the client line, then your calm reply that acknowledges, reframes and asks a question.",
  benefits: "Explaining why a website and a mobile app help this business, in plain words. Sections: Opening, What a website does for them, What an app adds (only if relevant), Common questions, Next step.",
  closing: "Closing professionally. Sections: Recap their needs, The recommendation, Price and what's included, Handling last-minute hesitation, Asking for the decision and agreeing the next step.",
  general: "A complete sales pitch. Sections: Opening, Customer needs, Service introduction, Benefits, Objection handling, Closing and next steps.",
};

function systemPrompt(kind: ScriptKind) {
  return (
    `You are ASTON, the sales-script writer for ${env.astonCompanyName}, a web agency. Services: website development (around ${env.astonWebsitePrice}), ` +
    `mobile app development (around ${env.astonAppPrice}), digital growth services, and AI-generated promotional ads for local businesses. ` +
    "A website demo and consultation are available on request. The goal of every script: invite the business owner to see a demo or schedule a meeting.\n" +
    `Write a ${KIND_LABEL[kind]} script. ${GUIDE[kind]}\n` +
    "Style: natural, warm, confident and easy to read aloud — short sentences, short lines, plain words, Indian small-business context. No robotic phrasing, no hype, no technical jargon, no pressure tactics.\n" +
    "Honesty: never invent client details, results, statistics, discounts, guarantees, deadlines or testimonials. Mention prices only as given (\"around …\"). " +
    "Unknown details become placeholders: [Business name], [Owner's name], [your name].\n" +
    'Lines: who="you" is what the salesperson says (1-3 sentences; may contain short inline directions like [Pause] or [Smile]); who="client" is a likely reply from the customer; who="note" is a stage direction on its own (e.g. "Wait for response").\n' +
    'Reply with JSON only: {"title": "<=60 chars", "kind": one of ' + JSON.stringify(SCRIPT_KINDS) + ', "businessType": "e.g. Café" or null, ' +
    '"details": {"businessName","industry","service","price","offer"} (only values given in the request or the defaults above; omit unknowns), ' +
    '"sections": [{"heading": "short heading", "lines": [{"who": "you"|"client"|"note", "text": "…"}]}]}'
  );
}

const cleanDetails = (d: unknown): ScriptDetails => {
  const p = detailsSchema.safeParse(d ?? {});
  const v = p.success ? p.data : {};
  return Object.fromEntries(Object.entries(v).filter(([, x]) => typeof x === "string" && x.trim()).map(([k, x]) => [k, redact(String(x))])) as ScriptDetails;
};

export interface GenerateInput { request: string; kind?: ScriptKind; details?: ScriptDetails; id?: string }

/** Generate a script with Groq; creates a draft, or replaces the content of `id` (regenerate). */
export async function generateScript(userId: string, input: GenerateInput, deps?: Partial<GroqDeps>): Promise<ScriptDTO> {
  const request = redact(input.request.trim()).slice(0, 1500);
  if (request.length < 3) throw new ScriptError("Tell ASTON what the script is for.");
  const kind = input.kind ?? detectKind(request);
  const details = cleanDetails(input.details);
  const existing = input.id ? await getScriptRow(userId, input.id) : null;

  let raw: { title?: string; kind?: string; businessType?: string | null; details?: unknown; sections?: unknown };
  try {
    const res = await groqChat({
      messages: [
        { role: "system", content: systemPrompt(kind) },
        { role: "user", content: `Request: ${request}${Object.keys(details).length ? `\nUse these details (they override anything else): ${JSON.stringify(details)}` : ""}` },
      ],
      response_format: { type: "json_object" },
      max_tokens: 3500,
      temperature: 0.7,
    }, { deps });
    raw = extractJson(res.choices[0]?.message?.content ?? "") as typeof raw;
  } catch (e) {
    if (e instanceof AstonAiUnavailable) throw new ScriptError(e.message, e.reason === "not_configured" || e.reason === "auth_error" ? 503 : 429);
    if (e instanceof SyntaxError || (e instanceof Error && /JSON/.test(e.message))) throw new ScriptError("The script came back unreadable — try Regenerate.", 502);
    throw e;
  }
  const sections = normalizeSections(raw.sections);
  if (!sections.length || sections.every((s) => s.lines.every((l) => l.who !== "you"))) throw new ScriptError("The script came back empty — try Regenerate.", 502);
  const finalKind = ((SCRIPT_KINDS as readonly string[]).includes(String(raw.kind)) && !input.kind ? raw.kind : kind) as ScriptKind;
  const mergedDetails = { ...cleanDetails(raw.details), ...details };
  const data = {
    title: redact(String(raw.title || KIND_LABEL[finalKind])).slice(0, 80),
    kind: finalKind,
    businessType: raw.businessType ? redact(String(raw.businessType)).slice(0, 40) : mergedDetails.industry ?? null,
    details: mergedDetails as object,
    content: sections as unknown as object,
    request,
  };
  const row = existing
    ? await getDb().astonScript.update({ where: { id: existing.id }, data })
    : await getDb().astonScript.create({ data: { userId, ...data } });
  await recordActivity(userId, { category: "business", agent: "ASTON", source: "aston", status: "success", action: `ASTON ${existing ? "rewrote" : "wrote"} a ${KIND_LABEL[finalKind]} script: ${row.title}`, importance: 2 });
  return toScriptDTO(row);
}

async function getScriptRow(userId: string, id: string): Promise<Row> {
  const row = await getDb().astonScript.findFirst({ where: { id, userId } });
  if (!row) throw new ScriptError("Script not found.", 404);
  return row;
}

export async function getScript(userId: string, id: string): Promise<ScriptDTO> {
  return toScriptDTO(await getScriptRow(userId, id));
}

export interface ScriptPatch { title?: string; kind?: ScriptKind; businessType?: string | null; details?: ScriptDetails; sections?: unknown; saved?: boolean }

export async function updateScript(userId: string, id: string, p: ScriptPatch): Promise<ScriptDTO> {
  await getScriptRow(userId, id);
  const data: Prisma.AstonScriptUpdateInput = {};
  if (p.title !== undefined) {
    const t = redact(p.title.trim()).slice(0, 80);
    if (!t) throw new ScriptError("A script needs a name.");
    data.title = t;
  }
  if (p.kind !== undefined) data.kind = p.kind;
  if (p.businessType !== undefined) data.businessType = p.businessType ? redact(p.businessType.trim()).slice(0, 40) || null : null;
  if (p.details !== undefined) data.details = cleanDetails(p.details) as object;
  if (p.sections !== undefined) {
    const sections = normalizeSections(p.sections);
    if (!sections.length) throw new ScriptError("The script can't be empty.");
    data.content = sections as unknown as object;
  }
  if (p.saved !== undefined) data.saved = p.saved;
  return toScriptDTO(await getDb().astonScript.update({ where: { id }, data }));
}

export async function deleteScript(userId: string, id: string): Promise<void> {
  await getScriptRow(userId, id);
  await getDb().astonScript.delete({ where: { id } });
}

/** Copy a script (to customise it for another business). The copy is saved. */
export async function duplicateScript(userId: string, id: string): Promise<ScriptDTO> {
  const r = await getScriptRow(userId, id);
  const row = await getDb().astonScript.create({
    data: { userId, title: `${r.title} (copy)`.slice(0, 80), kind: r.kind, businessType: r.businessType, details: (r.details ?? undefined) as object | undefined, content: r.content as object, request: r.request, saved: true },
  });
  return toScriptDTO(row);
}

export interface ListQuery { q?: string; kind?: string; businessType?: string; scope?: "saved" | "recent" }

export async function listScripts(userId: string, o: ListQuery = {}) {
  const q = o.q?.trim().slice(0, 80);
  const where: Prisma.AstonScriptWhereInput = {
    userId,
    ...(o.scope === "recent" ? {} : { saved: true }),
    ...(o.kind && (SCRIPT_KINDS as readonly string[]).includes(o.kind) ? { kind: o.kind } : {}),
    ...(o.businessType ? { businessType: { equals: o.businessType, mode: "insensitive" } } : {}),
    ...(q ? { OR: [{ title: { contains: q, mode: "insensitive" } }, { request: { contains: q, mode: "insensitive" } }, { businessType: { contains: q, mode: "insensitive" } }] } : {}),
  };
  const [rows, types] = await Promise.all([
    getDb().astonScript.findMany({ where, orderBy: { updatedAt: "desc" }, take: o.scope === "recent" ? 20 : 100 }),
    getDb().astonScript.findMany({ where: { userId, saved: true, businessType: { not: null } }, distinct: ["businessType"], select: { businessType: true }, take: 50 }),
  ]);
  return {
    scripts: rows.map((r) => {
      const d = toScriptDTO(r);
      return { id: d.id, title: d.title, kind: d.kind, kindLabel: d.kindLabel, businessType: d.businessType, saved: d.saved, updatedAt: d.updatedAt };
    }),
    businessTypes: types.map((t) => t.businessType!).sort(),
  };
}
